[package]
name = "tract-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.0"
ndarray-npy = "0.8.1"
tract-onnx = "0.17.9"
